using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace STRIDE.SourceGen;

[Generator]
public sealed class BlockRegistryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Filter op klassen met attributen die mogelijk StrideBlock zijn
        IncrementalValuesProvider<ClassDeclarationSyntax> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Where(static c => c is not null);

        // Koppel de compilatie-context om semantische types te valideren
        IncrementalValueProvider<(Compilation Compilation, ImmutableArray<ClassDeclarationSyntax> Classes)> compilationAndClasses =
            context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(source.Compilation, source.Classes, spc));
    }

    private static void Execute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes, SourceProductionContext context)
    {
        if (classes.IsEmpty) return;

        // Verkrijg het typesymbool van ons abstraction attribuut
        INamedTypeSymbol? attributeSymbol = compilation.GetTypeByMetadataName("STRIDE.Abstractions.StrideBlockAttribute");
        if (attributeSymbol is null) return;

        List<(string TypeString, string FullClassName)> discoveredBlocks = new();

        foreach (var classDeclaration in classes)
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            SemanticModel semanticModel = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol) continue;

            // Zoek naar het specifieke StrideBlock attribuut op de klasse
            foreach (var attributeData in classSymbol.GetAttributes())
            {
                if (SymbolEqualityComparer.Default.Equals(attributeData.AttributeClass, attributeSymbol))
                {
                    string typeString = attributeData.ConstructorArguments[0].Value?.ToString() ?? "";
                    string fullClassName = classSymbol.ToDisplayString();

                    if (!string.IsNullOrEmpty(typeString))
                    {
                        discoveredBlocks.Add((typeString, fullClassName));
                    }
                }
            }
        }

        if (discoveredBlocks.Count == 0) return;

        // Bouw de gegenereerde broncode met C# 14 functionaliteiten
        string generatedCode = GenerateRegistrySource(discoveredBlocks);
        context.AddSource("BlockRegistry.g.cs", SourceText.From(generatedCode, Encoding.UTF8));
    }

    private static string GenerateRegistrySource(List<(string TypeString, string FullClassName)> blocks)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using STRIDE.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("namespace STRIDE.Core;");
        sb.AppendLine();
        sb.AppendLine("public static partial class BlockRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static IBlock CreateBlock(string typeString, Dictionary<string, string> parameters)");
        sb.AppendLine("    {");
        sb.AppendLine("        return typeString switch");
        sb.AppendLine("        {");

        foreach (var (typeString, fullClassName) in blocks)
        {
            sb.AppendLine($"            \"{typeString}\" => new {fullClassName}(parameters),");
        }

        sb.AppendLine("            _ => throw new KeyNotFoundException($\"Block type '{typeString}' is not registered or compiled.\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}